#!groovy

node{
def projectsMap = [:]
projectsMap.put('admin-service', 'jijeesh/java-hello-world-with-maven')
projectsMap.put('alert-service', 'jijeesh/java-hello-world-with-maven')
projectsMap.put('auth-server', 'jijeesh/java-hello-world-with-maven')

def gitBranch = 'master'
  def mvnHome = tool 'maven36'
//  def jdkHome = tool 'jdk8'

  def gitBaseUrl = 'https://github.com/'
  //def server = Artifactory.server "artifactory"
    // Create an Artifactory Maven instance.
  //  def rtMaven = Artifactory.newMavenBuild()
    def buildInfo

    stage('Artifactory configuration') {
      echo 'Artifactory'
    }

    projectsMap.each { pName, gitUrl ->
        println "project name: ${pName} and Git url name ${gitUrl}"
        gitProjectUrl = gitBaseUrl + gitUrl
        println "Project url :" + gitProjectUrl
        dir("${pName}"){
          echo "${pName}"
          stage("${pName}_SCM") {
          git branch: gitBranch , url : gitProjectUrl
          "'${mvnHome}/bin/mvn' clean install"
        }
      //   stage("${pName}_Build") {
      //      // Run the maven build
      //      if (isUnix()) {
      //         "'${mvnHome}/bin/mvn' clean install"
      //      } else {
      //         bat(/"${mvnHome}\bin\mvn" clean install/)
      //      }
      // }

        }

      //   stage("${pName}_SCM") {
      // //  git branch: gitBranch , url : gitProjectUrl
      //   echo "${pName}"
      //   }


        };

          //End of Foreach



            stage("Test") {
                parallel(
                  "Firefox": {
                    echo 'firefox'
                  },
                  "IE": {
                   echo 'IE'
                  },
                  "Chrome": {
                    echo 'Chrome'
                  }
                )
            }



}
